### ISSUE TITLE
[Enhancement] Support creating ECC Keys

### ISSUE THREAD

**Issue by schurzi** [telekom-mms/ansible-collection-acme#87]
### Description

Currently we create a RSA 4096 bit key by default. It seems we also provide the possibility to inport an external key. I think we should also support creating ECC keys directly.

Arguably ECC keys are "better" in many regards so maybe we should even change the default.

### Additional information

https://github.com/T-Systems-MMS/ansible-collection-acme/blob/6f8124eb085260aba2f63cbeb64643ecc8c62199/roles/acme/tasks/create-keys.yml#L2-L8

**Comment by schurzi** [comment]
see also https://eff-certbot.readthedocs.io/en/stable/using.html#rsa-and-ecdsa-keys

**Comment by schurzi** [comment]
BSI Recommends in [TR-02102-2](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR02102/BSI-TR-02102-2.pdf?__blob=publicationFile&v=7):

- brainpoolP256r1
- brainpoolP384r1
- brainpoolP512r1
- secp256r1
- secp384r1
- secp521r1

**Comment by rndmh3ro** [comment]
We should probably make it configurable but default to secure defaults.
